name: "raiden-dynamo"

services:
  dynamodb:
    image: "amazon/dynamodb-local"
    ports:
      - "127.0.0.1:8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8000/shell || exit 1"]
      interval: "30s"
      start_period: "10s"
      timeout: "5s"
