use crate::{AttributeNames, IntoAttrName};

#[derive(Debug, Clone, PartialEq, Eq)]
enum AttrPathSegment {
    Name(String),
    Index(usize),
}

/// A structured DynamoDB document path.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AttrPath {
    segments: Vec<AttrPathSegment>,
}

impl AttrPath {
    /// Creates a path from a top-level attribute name.
    pub fn from_attr_name(name: impl Into<String>) -> Self {
        Self {
            segments: vec![AttrPathSegment::Name(name.into())],
        }
    }

    /// Appends a nested document field to the path.
    ///
    /// This is typically used with field accessors generated by
    /// `#[derive(RaidenDocument)]`.
    ///
    /// ```rust
    /// # use raiden::*;
    /// # #[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, RaidenDocument)]
    /// # struct Profile { level: usize }
    /// # #[derive(Raiden)]
    /// # #[raiden(table_name = "user")]
    /// # struct User { #[raiden(partition_key)] id: String, profile: Profile }
    /// let path = User::profile().field(Profile::level());
    /// ```
    pub fn field(mut self, field: impl IntoAttrPathSegment) -> Self {
        self.segments
            .push(AttrPathSegment::Name(field.into_attr_path_segment()));
        self
    }

    /// Appends a dynamic map key to the path.
    ///
    /// ```rust
    /// # use std::collections::HashMap;
    /// # use raiden::*;
    /// # #[derive(Raiden)]
    /// # #[raiden(table_name = "user")]
    /// # struct User { #[raiden(partition_key)] id: String, metadata: HashMap<String, usize> }
    /// let path = User::metadata().key("score");
    /// ```
    pub fn key(self, key: impl Into<String>) -> Self {
        self.field(key.into())
    }

    /// Appends a list index to the path.
    pub fn index(mut self, index: usize) -> Self {
        self.segments.push(AttrPathSegment::Index(index));
        self
    }

    pub(crate) fn expression(&self) -> String {
        let mut expression = String::new();

        for (index, segment) in self.segments.iter().enumerate() {
            match segment {
                AttrPathSegment::Name(name) => {
                    if !expression.is_empty() {
                        expression.push('.');
                    }
                    expression.push_str(&placeholder_for(name, index));
                }
                AttrPathSegment::Index(index) => {
                    expression.push('[');
                    expression.push_str(&index.to_string());
                    expression.push(']');
                }
            }
        }

        expression
    }

    pub(crate) fn attribute_names(&self) -> AttributeNames {
        let mut attribute_names = AttributeNames::new();

        for (index, segment) in self.segments.iter().enumerate() {
            if let AttrPathSegment::Name(name) = segment {
                attribute_names.insert(placeholder_for(name, index), name.clone());
            }
        }

        attribute_names
    }
}

impl std::fmt::Display for AttrPath {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.expression())
    }
}

fn placeholder_for(name: &str, index: usize) -> String {
    if name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
        format!("#{name}")
    } else {
        format!("#path{index}")
    }
}

pub trait IntoAttrPath: Sized {
    /// Converts the value into a structured document path.
    fn into_attr_path(self) -> AttrPath;
}

impl<T: IntoAttrName> IntoAttrPath for T {
    fn into_attr_path(self) -> AttrPath {
        AttrPath::from_attr_name(self.into_attr_name())
    }
}

impl IntoAttrPath for AttrPath {
    fn into_attr_path(self) -> AttrPath {
        self
    }
}

pub trait IntoAttrPathSegment: Sized {
    /// Converts the value into a single field segment for an attribute path.
    fn into_attr_path_segment(self) -> String;
}

impl<T: IntoAttrName> IntoAttrPathSegment for T {
    fn into_attr_path_segment(self) -> String {
        self.into_attr_name()
    }
}

impl IntoAttrPathSegment for String {
    fn into_attr_path_segment(self) -> String {
        self
    }
}

impl IntoAttrPathSegment for &str {
    fn into_attr_path_segment(self) -> String {
        self.to_owned()
    }
}

/// Extension methods for building DynamoDB document paths.
///
/// This trait is implemented for top-level attribute accessors generated by
/// `#[derive(Raiden)]` and for `AttrPath` itself, so nested paths can be built
/// fluently.
///
/// ```rust
/// # use std::collections::HashMap;
/// # use raiden::*;
/// # #[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, RaidenDocument)]
/// # struct Profile { level: usize }
/// # #[derive(Raiden)]
/// # #[raiden(table_name = "user")]
/// # struct User {
/// #     #[raiden(partition_key)]
/// #     id: String,
/// #     profile: Profile,
/// #     metadata: HashMap<String, usize>,
/// # }
/// let score_path = User::metadata().key("score");
/// let level_path = User::profile().field(Profile::level());
/// let first_level_path = User::profile().field(Profile::level()).index(0);
/// ```
pub trait AttrPathExt: IntoAttrPath + Sized {
    /// Appends a nested field segment.
    fn field(self, field: impl IntoAttrPathSegment) -> AttrPath {
        self.into_attr_path().field(field)
    }

    /// Appends a dynamic map key segment.
    fn key(self, key: impl Into<String>) -> AttrPath {
        self.into_attr_path().key(key)
    }

    /// Appends a list index segment.
    fn index(self, index: usize) -> AttrPath {
        self.into_attr_path().index(index)
    }
}

impl<T: IntoAttrPath> AttrPathExt for T {}
